{
    "sourceFile": "back-end/src/app/middlewares/catchAsyncError.js",
    "activeCommit": 0,
    "commits": [
        {
            "activePatchIndex": 1,
            "patches": [
                {
                    "date": 1653840461541,
                    "content": "Index: \n===================================================================\n--- \n+++ \n"
                },
                {
                    "date": 1654618544084,
                    "content": "Index: \n===================================================================\n--- \n+++ \n@@ -1,3 +1,3 @@\n-module.exports = (thefunc) => (req, res, next) => {\r\n-  Promise.resolve(thefunc(req, res, next)).catch(next);\r\n-};\r\n+// module.exports = (thefunc) => (req, res, next) => {\r\n+//   Promise.resolve(thefunc(req, res, next)).catch(next);\r\n+// };\r\n"
                }
            ],
            "date": 1653840461541,
            "name": "Commit-0",
            "content": "module.exports = (thefunc) => (req, res, next) => {\r\n  Promise.resolve(thefunc(req, res, next)).catch(next);\r\n};\r\n"
        }
    ]
}